modLoader="javafml"
loaderVersion="[32,)" 
issueTrackerURL="https://github.com/TeamFelnull/EpochTechnologies/issues"
logoFile="logo.png" 
[[mods]]
modId="epochtechnologies"
version="${file.jarVersion}" 
displayName="Epoch Technologies"
updateJSONURL="https://raw.githubusercontent.com/TeamFelnull/EpochTechnologies/master/update_check.json" 
displayURL="https://github.com/TeamFelnull/EpochTechnologies" 
credits="TeamFelNull.Snow,Ramely or hanzaisya"
authors="MORIMORI0317" 
description="Thank you for downloading!\nThis mod is The Ikisugi Industrial revolution."

[[dependencies.epochtechnologies]]
    modId="otyacraftengine"
    mandatory=true
    versionRange="[1.0,)"
    ordering="NONE"
    side="BOTH"
